/**
 * PDF Reports Utility
 * Generates and downloads beautifully formatted PDF reports for teachers
 */

class ReportService {
    constructor() {
        this.primaryColor = [16, 185, 129];    // Theme Green (#10b981)
        this.secondaryColor = [4, 120, 87];   // Darker Green (#047857)
        this.textColor = [55, 65, 81];        // Charcoal Gray (#374151)
        this.lightGray = [243, 244, 246];     // Light Background (#f3f4f6)
    }

    /**
     * Helper to verify if jsPDF is loaded
     */
    checkLibraries() {
        if (!window.jspdf) {
            throw new Error("jsPDF library is not loaded. Please connect to the internet.");
        }
    }

    /**
     * Generate and download Daily Attendance Report
     */
    async generateDailyReport(date, subject, attendanceRecords, students) {
        this.checkLibraries();
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

        // Compile mapping of student details
        const studentMap = {};
        students.forEach(s => {
            studentMap[s.studentId] = s;
        });

        // 1. Title and Header Card
        this.drawHeader(doc, "Daily Attendance Report");
        
        // Meta details block
        let y = 35;
        doc.setFontSize(10);
        doc.setTextColor(...this.textColor);
        doc.setFont("helvetica", "normal");
        
        doc.text(`School Name: ${window.db.getCurrentTeacher()?.schoolName || 'Rural Public School'}`, 15, y);
        doc.text(`Teacher: ${window.db.getCurrentTeacher()?.name || 'Authorized Instructor'}`, 15, y + 5);
        
        doc.text(`Date: ${date}`, 120, y);
        doc.text(`Subject: ${subject.name} (${subject.code})`, 120, y + 5);

        // Stats summary cards
        y += 15;
        const total = students.length;
        const presentCount = attendanceRecords.filter(r => r.status === 'Present').length;
        const absentCount = total - presentCount;
        const rate = total > 0 ? Math.round((presentCount / total) * 100) : 0;

        this.drawStatsCards(doc, y, presentCount, absentCount, rate);

        // 2. Table Data construction
        y += 25;
        const tableBody = students.map((student, idx) => {
            const record = attendanceRecords.find(r => r.studentId === student.studentId);
            const status = record ? record.status : 'Absent'; // Default to Absent if no record
            return [
                idx + 1,
                student.rollNumber || 'N/A',
                student.name,
                `${student.class}-${student.section}`,
                status
            ];
        });

        // Style the table
        doc.autoTable({
            startY: y,
            head: [['S.No', 'Roll No', 'Student Name', 'Class/Sec', 'Status']],
            body: tableBody,
            headStyles: { fillStyle: 'F', fillColor: this.primaryColor, textColor: [255, 255, 255], fontStyle: 'bold' },
            alternateRowStyles: { fillColor: this.lightGray },
            margin: { left: 15, right: 15 },
            styles: { fontSize: 9, font: 'helvetica' },
            columnStyles: {
                0: { cellWidth: 15 },
                1: { cellWidth: 25 },
                2: { cellWidth: 80 },
                3: { cellWidth: 30 },
                4: { cellWidth: 30, fontStyle: 'bold' }
            },
            didParseCell: function(data) {
                // Color code the status
                if (data.column.index === 4 && data.cell.section === 'body') {
                    if (data.cell.text[0] === 'Present') {
                        data.cell.styles.textColor = [16, 185, 129]; // Green
                    } else {
                        data.cell.styles.textColor = [239, 68, 68]; // Red
                    }
                }
            }
        });

        // Add Signature / Footer lines
        const finalY = doc.previousAutoTable.finalY + 20;
        doc.setFontSize(9);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by Automated AI Face Attendance System for Rural Schools", 15, 280);
        
        doc.setDrawColor(200, 200, 200);
        doc.line(140, finalY + 15, 195, finalY + 15);
        doc.setTextColor(...this.textColor);
        doc.text("Teacher Signature", 153, finalY + 20);

        doc.save(`Attendance_Report_${subject.code}_${date}.pdf`);
    }

    /**
     * Generate Monthly Report
     */
    async generateMonthlyReport(yearMonth, subject, attendanceRecords, students) {
        this.checkLibraries();
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

        this.drawHeader(doc, "Monthly Attendance Sheet");

        let y = 35;
        doc.setFontSize(10);
        doc.setTextColor(...this.textColor);
        
        doc.text(`School Name: ${window.db.getCurrentTeacher()?.schoolName || 'Rural Public School'}`, 15, y);
        doc.text(`Teacher: ${window.db.getCurrentTeacher()?.name || 'Authorized Instructor'}`, 15, y + 5);
        
        doc.text(`Month: ${yearMonth}`, 120, y);
        doc.text(`Subject: ${subject.name} (${subject.code})`, 120, y + 5);

        // Compile student stats for the month
        // We find the list of unique dates recorded this month to compute percentages
        const monthlyDates = Array.from(new Set(attendanceRecords.map(r => r.date))).sort();
        const totalSessions = monthlyDates.length;

        // Stats card computations
        let totalPresentAll = 0;
        const studentStats = students.map((student, idx) => {
            const studentRecs = attendanceRecords.filter(r => r.studentId === student.studentId);
            const presentDays = studentRecs.filter(r => r.status === 'Present').length;
            const absentDays = totalSessions - presentDays;
            const percentage = totalSessions > 0 ? Math.round((presentDays / totalSessions) * 100) : 0;
            totalPresentAll += presentDays;

            return {
                sNo: idx + 1,
                roll: student.rollNumber || 'N/A',
                name: student.name,
                present: presentDays,
                absent: absentDays,
                percent: `${percentage}%`,
                rawPercent: percentage
            };
        });

        const avgMonthlyRate = students.length > 0 && totalSessions > 0 ? 
            Math.round((totalPresentAll / (students.length * totalSessions)) * 100) : 0;

        y += 15;
        this.drawStatsCards(doc, y, totalSessions, `${students.length} Students`, `${avgMonthlyRate}%`);
        
        // Adjust labels for middle card
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("Total Sessions", 26, y + 10);
        doc.text("Enrolled Students", 89, y + 10);
        doc.text("Avg Attendance Rate", 148, y + 10);

        y += 25;
        doc.autoTable({
            startY: y,
            head: [['S.No', 'Roll No', 'Student Name', 'Present Days', 'Absent Days', 'Percentage']],
            body: studentStats.map(s => [s.sNo, s.roll, s.name, s.present, s.absent, s.percent]),
            headStyles: { fillStyle: 'F', fillColor: this.primaryColor, textColor: [255, 255, 255], fontStyle: 'bold' },
            alternateRowStyles: { fillColor: this.lightGray },
            margin: { left: 15, right: 15 },
            styles: { fontSize: 9, font: 'helvetica' },
            columnStyles: {
                0: { cellWidth: 15 },
                1: { cellWidth: 25 },
                2: { cellWidth: 75 },
                3: { cellWidth: 25 },
                4: { cellWidth: 25 },
                5: { cellWidth: 25, fontStyle: 'bold' }
            },
            didParseCell: function(data) {
                if (data.column.index === 5 && data.cell.section === 'body') {
                    const pctVal = parseInt(data.cell.text[0]);
                    if (pctVal >= 75) {
                        data.cell.styles.textColor = [16, 185, 129]; // Safe Green
                    } else if (pctVal >= 50) {
                        data.cell.styles.textColor = [245, 158, 11]; // Yellow Warn
                    } else {
                        data.cell.styles.textColor = [239, 68, 68]; // Low Red
                    }
                }
            }
        });

        // Footer
        doc.setFontSize(9);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by Automated AI Face Attendance System for Rural Schools", 15, 280);

        doc.save(`Monthly_Attendance_Sheet_${subject.code}_${yearMonth}.pdf`);
    }

    /**
     * Draw standard title and top decoration
     */
    drawHeader(doc, titleText) {
        // Decorative top bar
        doc.setFillColor(...this.secondaryColor);
        doc.rect(0, 0, 210, 12, 'F');
        
        doc.setFillColor(...this.primaryColor);
        doc.rect(0, 12, 210, 2, 'F');

        // Main Title
        doc.setFontSize(20);
        doc.setTextColor(...this.secondaryColor);
        doc.setFont("helvetica", "bold");
        doc.text(titleText, 15, 25);
        
        // Underline title
        doc.setDrawColor(...this.primaryColor);
        doc.setLineWidth(0.8);
        doc.line(15, 27, 85, 27);
    }

    /**
     * Draw statistics blocks
     */
    drawStatsCards(doc, startY, leftVal, middleVal, rightVal) {
        // Render 3 stats boxes
        const boxWidth = 56;
        const boxHeight = 15;
        const cardXCoords = [15, 77, 139];
        const cardData = [
            { label: "PRESENT", val: leftVal, bg: [236, 253, 245], border: [16, 185, 129] },
            { label: "ABSENT", val: middleVal, bg: [254, 242, 242], border: [239, 68, 68] },
            { label: "PERCENTAGE", val: rightVal, bg: [239, 246, 255], border: [59, 130, 246] }
        ];

        cardData.forEach((card, idx) => {
            const x = cardXCoords[idx];
            // Draw card bg
            doc.setFillColor(...card.bg);
            doc.setDrawColor(...card.border);
            doc.setLineWidth(0.3);
            doc.rect(x, startY, boxWidth, boxHeight, 'FD');

            // Draw Value
            doc.setFontSize(14);
            doc.setTextColor(...card.border);
            doc.setFont("helvetica", "bold");
            // Center aligning simple logic
            const strVal = String(card.val);
            const textWidth = doc.getStringUnitWidth(strVal) * doc.internal.getFontSize() / doc.internal.scaleFactor;
            const textX = x + (boxWidth - textWidth) / 2;
            doc.text(strVal, textX, startY + 9);

            // Draw Label
            doc.setFontSize(7);
            doc.setTextColor(120, 120, 120);
            const lblWidth = doc.getStringUnitWidth(card.label) * doc.internal.getFontSize() / doc.internal.scaleFactor;
            const lblX = x + (boxWidth - lblWidth) / 2;
            doc.text(card.label, lblX, startY + 13);
        });
    }
}

// Instantiate and expose globally
const reportService = new ReportService();
window.reportService = reportService;
